### PR TITLE
Install completions, shim bunx

### PR DESCRIPTION
**Pull request by iloveitaly**
Related discussion: https://discord.com/channels/876711213126520882/876711213126520885/1063108726984298556

### CODE REVIEW

**Comment by cometkim** [comment]
It would fail with this message, and even if it succeeds, it works only for zsh.

```bash
❯ bun completions
error: Could not find a directory to install completions in.

zsh tip: One of the directories in $fpath might work. If you use oh-my-zsh, try mkdir $HOME/.oh-my-zsh/completions; and bun completions again
.
Please either pipe it:
   bun completions > /to/a/file

 Or pass a directory:

   bun completions /my/completions/dir
```

**Comment by cometkim** [comment]
I'll add a universal alias for the `bun x` command for v0.4.0+. completions require each user to manually edit their rc files.

**Comment by iloveitaly** [comment]
@cometkim should we only execute completions if we are in zsh?

Not sure what you mean by `I'll add a universal alias for the bun x command for v0.4.0+. `

**Comment by cometkim** [comment]
just something like this:
```
echo 'bun x "$@"' > bunx && chmod +x bunx
```

**Comment by iloveitaly** [comment]
I wonder if it's better to execute the completions command in case there
are more additions/symlinks generated automatically in the future. Wdyt?

**Comment by cometkim** [comment]
asdf users wouldn't want any changes outside the $install_path. Bun completions are for changing the zhsrc file and registering autoload, which are not intended to be installed by the asdf plugin. Users can do it themselves after installing the desired version of the bun.

**Comment by iloveitaly** [comment]
Makes sense. Trying to limit churn to the asdf folders. Thanks for the explanation!

**Pull request closed without merging**
